### ISSUE TITLE
1.810 changes my vote to Stay after a period of time

### ISSUE THREAD

**Issue by TrantaLocked** [vartan/robin-grow#102]
New bug it seems.

**Comment by dkisselev** [comment]
update() sets the vote from whatever is configured in the settings, https://github.com/vartan/robin-grow/blob/master/robin.user.js#L209-L221

setVote is the only thing that changes the vote parameter and only exists in 4 places in the code: https://github.com/vartan/robin-grow/blob/master/robin.user.js#L81-L89

Maybe the settings parameter defaulted to stay and you need to click the Grow button once after updating to save your preference?

**Comment by alejandrocoria** [comment]
The script changes the vote to Stay after I mute a user who voted that way. I do not know if it is the same bug or not. The oddest thing is that it does after a few seconds of mute.

**Comment by dkisselev** [comment]
You're right, great catch.

Users in the user list have the same class as the stay button: `.robin--vote-class--continue`, so clicking one of them triggers setVote like I mentioned above.

This needs a PR to make the selector that searches for those buttons to be more specific (I'm sure they were at one point but someone recently undid it).

It only happens a few seconds later because update() is only set to run every 10 seconds.

**Comment by vartan** [comment]
Wow that is a GREAT catch guys.

I have updated this in the newest update. Can anyone confirm?

**Comment by TrantaLocked** [comment]
It's no longer an issue for me on the latest update.
