### ISSUE TITLE
Chat tab crashes with "aw, snap" in Chrome

### ISSUE THREAD

**Issue by deegles** [vartan/robin-grow#126]
Not sure if this is because of the script, tampermonkey or the page though. It seems to happen after about 8 hours.

Is it possible to detect a crash and reload the page? If not it might help to have a periodic full page refresh.

**Comment by vartan** [comment]
Can anyone else confirm this is a problem? I think i had it running for about 12hrs last night

**Comment by deegles** [comment]
(sorry for the double-post)

**Comment by dashed** [comment]
@deegles which version?

**Comment by tetra-fox** [comment]
well it isn't possible to detect a crash because the entire page including the scripts that are added through tampermonkey crash

and then the script that was running can't do anything (ex. reload the page)

**Comment by deegles** [comment]
I believe it was at this version (last one of april 2nd): https://github.com/vartan/robin-grow/tree/c61283e5a1566cdad03f5b7fcf494a69c8495416

**Comment by OkanEsen** [comment]
Maybe reload the whole page every x hours based on the room size?

**Comment by dashed** [comment]
> Maybe reload the whole page every x hours based on the room size?

Please no.

---

The script needs to be optimized. 

For example: this autoincrements forever: https://github.com/vartan/robin-grow/blob/master/robin.user.js#L337

**Comment by dkisselev** [comment]
I just set up another script that forces a refresh every 5 minutes (on the computer that I keep running specifically to keep my chats going) _shrug_.

It's not ideal, but since page crashes tend to happen so rarely (and there are multiple different ways it can happen), I've found that's the only sure-fire way to ensure that everything stays running through the nights. 

This script/project works well but development is happening so fast and there have been so many dirty merges that I personally don't really trust it for "production" use any more.

With spam list saving submitted as a PR, refreshes aren't going to be as painful.

Perhaps we could add a setting, let people keep using the current/improved "smart" refreshing by default, but also allow explicit force refreshing every x minutes as an option for overnights when you don't care about watching the chat and want a higher chance of making it through the night?

**Comment by OkanEsen** [comment]
@deegles I'm using a version which I optimized further, as I noticed some strange CPU spikes throughout the robin session. The script now runs for several hours and I've yet to encounter a crash.

The main issue of the whole script is the `findAndHideSpam()` method and specifically this part https://github.com/vartan/robin-grow/blob/master/robin.user.js#L360 with three `$.each` iterations, which is fired every time a message is not classified as a bot message.

The data structure needs some serious rethinking and usage of jQuery should be replaced with native methods but right now we should solely focus on `findAndHideSpam()`.

**Comment by dashed** [comment]
@OkanEsen if this chat thing survives beyond the 8th.. I'd optimize it.

**Comment by vartan** [comment]
@dashed that's basically where I stand with this too haha.

Combining the $each wouldn't make that much of a difference, we really just have to implement that directly into the mutation stuff without doing any looping at all.

**Comment by vartan** [comment]
Chrome crashing makes it sound like there's a memory leak though, which would be a separate issue. Is anyone familiar with detecting memory leaks in JS?

**Comment by deegles** [comment]
I believe the memory leak is in the $spamCounts object. $messages is pruned but $spamCounts is not, so it will just keep growing.

**Comment by deegles** [comment]
We had a good run!
