### ISSUE TITLE
Swing from grow to stay if room is going to RIP?

### ISSUE THREAD

**Issue by marceltt** [vartan/robin-grow#71]
I was wondering if this is possible, maybe with less than 2 mins left, if GROWS are outvoted then switch to STAY in effort to save the room to a subreddit.

**Comment by Phoenix616** [comment]
My previous fix wouldn't really help much as it just checked whether or not the growers manage to gain  the majority and that's not how rooms usually die: They mostly die due to people going afk due to no merge occurring and then being afk when a merge finally arrives, therefor killing the room.

The best way to implement such a feature would therefore be to switch to stay when the room couldn't merge for a set amount of time. This should probably include a settings option to define how big a chat should be before switching to stay. (Something around 2000 seems appropriate if you take KuPrlits as an example)

One could also calculate different timezones (europe and us night) and the amount of people already afk into the switcher, not sure if you even can get all of the afk ones 'though.

**Comment by vartan** [comment]
This isn't really the point of the bot, I'm gonna go ahead and close this.
